config/routes.rb
Rails.application.routes.draw do
  root 'static_page#top'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  validates :user_id, presence: true
  validates :content, presence: true
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  private
   def logged_in_user
     unless logged_in?
       redirect_to login_url
     end
   end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_parameter)
    @post.user_id = current_user.id
    if @post.save
      redirect_to root_url
    else
      render 'new'
    end
  end

  def destroy
  end

  private

  def post_parameter
    params.require(:post).permit(:content)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(login_id: params[:session][:login_id].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to root_url
    else
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_page_controller.rb
class StaticPageController < ApplicationController
  def top
    @posts = Post.all.includes(:user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(signup_strong_arameters)
    if @user.save
      log_in(@user)
      redirect_to root_url
    else
      render 'new'
    end
  end

  def show
  end

  private
  def signup_strong_arameters
    params.require(:user).permit(:name, :login_id, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def current_user?(user)
    user == current_user
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title DataAlignment
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
  %body
    = yield

app/views/posts/new.html.haml
%h1 コメントする
= form_for @post do |f|
  = f.label :content
  = f.text_field :content
  = f.submit

app/views/static_page/top.html.haml
%h1
  This is top page!

- if logged_in?
  %div
    = current_user.name
  = link_to "logout", logout_path, data: { "turbo-method": :delete }
  = link_to "post comment", new_post_path
- else
  = link_to "signup", new_user_path
  = link_to "login", login_path

%h2 全てのコメント
- @posts.each do |post|
  %div
    = post.user.name
  %div
    = post.content
  %br

app/views/users/create.html.haml
%h1 Users#create
%p Find me in app/views/users/create.html.haml

app/views/users/new.html.haml
%h1 Users#new
%p Find me in app/views/users/new.html.haml

= form_for @user do |f|
  = f.label :name
  = f.text_field :name
  = f.label :login_id
  = f.text_field :login_id
  = f.label :password
  = f.password_field :password
  = f.label :password_confirmation
  = f.password_field :password_confirmation
  = f.submit

app/views/users/show.html.haml
%h1 Users#show
%p Find me in app/views/users/show.html.haml